---
title: "smet_results_analysis"
author: "MKAUFMAN"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##import GPP and ER daily means from SM results and combine
```{r import, echo=FALSE}
folder<-'C:/Users/kauf093/OneDrive - PNNL/Documents/GitHub/SSS_metabolism/StreamMetabolizer_runs/final_results/'
filenamelist<-list.files(folder, pattern='daily_prediction_results')

SITE_IDlist<-sapply(strsplit(filenamelist, "_"), "[", 2)
PARENT_IDlist<-sapply(strsplit(filenamelist, "_"), "[", 1)

depthfolder<-'C:/Users/kauf093/OneDrive - PNNL/Spatial Study 2022/SSS_Data_Processing/5 - Publish_Ready_StreamMetabolizer_Input/'
depthfilenamelist<-list.files(depthfolder, pattern='csv')
depthPARENT_IDlist<-sapply(strsplit(depthfilenamelist, "_"), "[", 1)


#create output dataframe
SMresults <- data.frame(matrix(ncol = 11, nrow = 0))
colnames(SMresults) <- c("Parent_ID","Site_ID", "daysofdata", "ERdailymeanmean_gO2/m2day", "GPPdailymeanmean_gO2/m2day", "K600dailymeanmean_m/day","mean_depth_m","ERdailymeanmean_gO2/m3day","GPPdailymeanmean_gO2/m3day","K600vsERrsq","K600vsERp")

#start loop
for(i in 1:length(PARENT_IDlist)) { 
#for(i in 1) { 
data = read.csv(paste(folder,filenamelist[i],sep=''),header=T)
numdays<-length(data$ER_daily_mean[!is.na(data$ER_daily_mean)])
ERdailymeanmean<-mean(data$ER_daily_mean[!is.na(data$ER_daily_mean)])
GPPdailymeanmean<-mean(data$GPP_daily_mean[!is.na(data$GPP_daily_mean)])
K600dailymeanmean<-mean(data$K600_daily_mean[!is.na(data$K600_daily_mean)])

depthfilenumber<-which(depthPARENT_IDlist == PARENT_IDlist[i])

depthdata<-read.csv(paste(depthfolder,depthfilenamelist[depthfilenumber],sep=''),header=T,skip=8)
meandepthm<-mean(depthdata$Depth,na.rm=TRUE)

ERdailymeanmeanm3<-ERdailymeanmean/meandepthm
GPPdailymeanmeanm3<-GPPdailymeanmean/meandepthm

lmK600ER = lm(ER_daily_mean~K600_daily_mean, data = data) #Create the linear regression
K600vsERp=summary(lmK600ER)$coefficients[2,4]
K600vsERrsq=summary(lmK600ER)$r.squared

SMresults[nrow(SMresults) + 1,] = c(PARENT_IDlist[i],SITE_IDlist[i], numdays,ERdailymeanmean,GPPdailymeanmean,K600dailymeanmean,meandepthm,ERdailymeanmeanm3,GPPdailymeanmeanm3,K600vsERrsq,K600vsERp)
}

```
##write CSV outupt
```{r output, echo=FALSE}
write.csv(SMresults, paste(folder,"combined_results_no_special_cases.csv",sep=""), row.names=FALSE)
```
