---
title: "Untitled"
author: "MKAUFMAN"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(reshape)

data<-read.csv("C:/Users/kauf093/OneDrive - PNNL/Spatial Study 2022/04_Minidot/03_ProcessedData/SSS_MiniDOT_S01_trimmed.csv")
tt<-data$Time_unix
DO<-data$DO_mg_l

DObasis201 = create.fourier.basis(rangeval = range(tt),nbasis = 201)
DObasis301 = create.fourier.basis(rangeval = range(tt),nbasis = 301)
DObasis401 = create.fourier.basis(rangeval = range(tt),nbasis = 401)
DOfourier201.fd = smooth.basis(argvals = tt, y = DO,fdParobj = DObasis201)$fd
DOfourier301.fd = smooth.basis(argvals = tt, y = DO,fdParobj = DObasis301)$fd
DOfourier401.fd = smooth.basis(argvals = tt, y = DO,fdParobj = DObasis401)$fd
DO201 = eval.fd(tt,DOfourier201.fd)
DO301 = eval.fd(tt,DOfourier301.fd)
DO401 = eval.fd(tt,DOfourier401.fd)
DOdo = setNames(data.frame(tt,data$Date_Time_PST,DO,DO201,DO301,DO401),c("unixtime","Date_Time_PST","DO","Fourier201","Fourier301","Fourier401"))

```
```{r}

write.csv(DOdo, "C:/Users/kauf093/OneDrive - PNNL/Spatial Study 2022/04_Minidot/03_ProcessedData/test/F_S01.csv", row.names=TRUE)

```


```{r}

plot(tt, DO, type = "l", lty = 1)
plot(tt, DO200, type = "l", lty = 1)
plot(tt, DO300, type = "l", lty = 1)
plot(tt, DO400, type = "l", lty = 1)

```

```{r}

stats <- data.frame(matrix(ncol = 2, nrow = 0))
x <- c("basis", "RMSE")
colnames(stats) <- x

x=c(10,50,100,200,300,355,356,357,358,359,361,362,363,364,365,370,400,450)
for (basis in x){
print(basis)
DObasis = create.fourier.basis(rangeval = range(tt),nbasis = basis)
DOfourier.fd = smooth.basis(argvals = tt, y = DO,fdParobj = DObasis)$fd
DOsmooth = eval.fd(tt,DOfourier.fd)
DOdo = setNames(data.frame(tt,data$Date_Time_PST,DO,DOsmooth),c("unixtime","Date_Time_PST","DO","Fourier_smoothed"))
errorsq=(DOdo$Fourier_smoothed-DOdo$DO)^2
RMSE=sqrt(sum(errorsq)/length(tt))

stats[nrow(stats) + 1,] = c(basis, RMSE)
}

```
```{r}
basis=359
DObasis = create.fourier.basis(rangeval = range(tt),nbasis = basis)
DOfourier.fd = smooth.basis(argvals = tt, y = DO,fdParobj = DObasis)$fd
DOsmooth = eval.fd(tt,DOfourier.fd)
pcterror=100*abs(DO-DOsmooth)/DO
DOdo = setNames(data.frame(tt,data$Date_Time_PST,DO,DOsmooth,pcterror,DO),c("unixtime","Date_Time_PST","DO","Fourier_smoothed","pcterror","error_reduced"))
```

```{r}
DOdo$error_reduced<-DOdo$DO
threshold=0.5
DOdo$error_reduced[DOdo$pcterror>threshold]<-DOdo$Fourier_smoothed[DOdo$pcterror>threshold]
write.csv(DOdo, "C:/Users/kauf093/OneDrive - PNNL/Spatial Study 2022/04_Minidot/03_ProcessedData/test/error_reduced_S01.csv", row.names=TRUE)

```


