---
title: "SS22 Minidot Data summary and Visualization "
author: "Xinming Lin"
date: "09/15/2022"
output:
  html_document:
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: no
    toc_depth: 4
    theme: lumen
always_allow_html: yes
knit: (
  function(inputFile, encoding) { 

    pSubTitle <- paste0("SS22 Minidot Data summary and Visualization ",Sys.Date())

    rmarkdown::render( 
      input       = inputFile, 
      encoding    = encoding, 
      params      = list(sub_title = pSubTitle),      
      output_file = pSubTitle)})
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

### Loading R libraries
```{r libraries, echo = FALSE, warning=FALSE, message=FALSE,results="hide"}
rm(list=ls(all=T))
library(zoo)
library(dplyr)
library(forecast)
library(tidyr)
library(devtools)
library(plyr)
library(readr)
library(lubridate)
library(htmlwidgets)
library(ggplot2)
library(gridExtra) # for arranging plots
library(grid)
library(plotly)
library(ggthemes);library(ggpubr)
library(stringr)
library(anomalize)
library(tibbletime)
library(imputeTS)
library(stats)
library(Rssa)
library(knitr)
library(dygraphs)
sdir = 'C:/Users/linx882/PNNL/RC-2, River Corridor SFA - Spatial Study 2022'
#source('./funs.R')
source(file.path(sdir,"SSS_Data_Processing",'R_Scripts','funs.R'))
indir = file.path(sdir,"04_Minidot")
outdir=file.path(sdir,"SSS_Data_Processing")
############################################################
# read in metadata
mindir<-file.path(sdir,'06_Metadata')
mfile<- 'SSS_Metadata_Deploy_Sample_Retrieve_2022-11-21.csv'
metadata<-read_metadata(indir=mindir,file= mfile)
############################################################
#Minidot data files
files <-list.files(file.path(indir,'03_ProcessedData'))
sites = unlist(lapply(files,function(i){str_split(i, '_')[[1]][3]}))
files
```

# data processing and outlier detection 
```{r data, echo=FALSE, results='asis', fig.keep='all', message = FALSE, warning = FALSE}
## minidot timeseries data
#filenames <-list.files(file.path(indir,'03_ProcessedData'),full.names=TRUE) #list.files(file.path(indir,'03_ProcessedData'))
#tsdata<- lapply(files,function(i){process_data(file.path(indir,'03_ProcessedData'),i,alpha=0.02)})
#htmltools::tagList(lapply(tsdata, function(x) { tsplot_ly(x, save=FALSE) }))

# for (f in 1:length(files)){
#   #cat("### Minidot timeseries data: ", f, "\n")
#   data = process_data(indir=file.path(indir,'03_ProcessedData'),filename=files[f],alpha=0.02)
#   dygraph(data[,c(2:4)], main = "New Haven Temperatures", ylab = "Temp (F)") 
#   
# }

for (f in 1:length(files)){
  #cat("### Minidot timeseries data: ", f, "\n")
  data = process_data(indir=file.path(indir,'03_ProcessedData'),filename=files[f],alpha=0.05)
  ## time series plot
  #tsplot_ly(data,save=FALSE)
  cols=c("Temp_degC","DO_mg_l","DO_sat")
  for (i in 1:length(cols)) {
    tidx<-which((data[paste0(cols[i],'_outlier')]=='Yes')&(!is.na(data[,cols[i]])))
    if(length(tidx)>0){
      data[tidx,paste0(cols[i],'_outlier')] = data[tidx,cols[i]]
    }
    data[,paste0(cols[i],'_outlier')]<-as.numeric(data[,paste0(cols[i],'_outlier')])
  }
  data<- data.table(data)
  ##
  dygraph(data[,c("Date_Time_PST", "Temp_degC","Temp_degC_outlier")],main = paste0("Temperature (",sites[f] ,")") ,
        ylab = "Temperature (C)", group = sites[f]) %>%
  dySeries("Temp_degC", drawPoints = TRUE, pointShape = "square", color = "black") %>%
  dySeries(paste0("Temp_degC",'_outlier'), drawPoints = TRUE, pointShape = "circle", color = "red")%>% 
  dyRangeSelector()
  ##
  dygraph(data[,c("Date_Time_PST", "DO_mg_l","DO_mg_l_outlier")],main = paste0("Dissolved Oxygen (",sites[f] ,")") ,
        ylab = "Dissolved Oxygen(mg/L)", group = sites[f]) %>%
  dySeries("DO_mg_l", drawPoints = TRUE, pointShape = "square", color = "black") %>%
  dySeries(paste0("DO_mg_l",'_outlier'), drawPoints = TRUE, pointShape = "circle", color = "red")%>%
  dyRangeSelector()
  ##
  dygraph(data[,c("Date_Time_PST", "DO_sat","DO_sat_outlier")],
          main = paste0("Dissolved Oxygen Sturation (",sites[f],")"),
          ylab = "Dissolved Oxygen Sturation(%)", group = sites[f]) %>%
  dySeries("DO_sat", drawPoints = TRUE, pointShape = "square", color = "black") %>%
  dySeries(paste0("DO_sat",'_outlier'), drawPoints = TRUE, pointShape = "circle", color = "red")%>%
  dyRangeSelector()

}

# # Render the outputs
# for(j in 1:length(plot_list)){
#   x <- plot_list[[j]]
# 
#   if(inherits(x, "character")){
#     cat("\n")
#     cat(x)
#   } else if(inherits(x, "knitr_kable")){
#     cat("\n")
#     print(x)
#   }
#   else {
#     # print the html piece of the htmlwidgets
#     cat("\n")
#     cat(htmltools::renderTags(as.widget(x))$html)
#   }
# }

#write.csv(odata,file.path(outdir,'SSS_MiniDOT_outliers.csv'),na = "NA",row.names = FALSE)
#write.csv(sumdata,file.path(outdir,'SSS_MiniDOT_summary_statistics.csv'),na = "NA",row.names = FALSE)

```

